# NumPy
## Practice Problems

### 1. The formula for exponential growth is `population_size = N0 *e**rt`, where `N0` is the initial population, `e` is the exponential function, `r` is the rate, and `t` is time. Using this:

1.   Set the initial population, `N0`, as 100 and the growth rate, `r`, as 0.4
2.   Use the suitable `numpy` function to generate an array of time points, `t`, which go from 0 to 10 seconds, in 0.2 second increments.
3.   Write an expression to evaluate `population_size`, which should be an array of the population size for each time point in `t`.
4.   Create a new variable called `population_size_noise`, use the same expression you wrote in parts (3), and add noise to the population at each time point. Do this by adding an expression that uses a `numpy` function to generate a random value for each time point drawn from a normal distribution of `mean=0` and `stdev=250` (i.e., population_size_noise = expression_from_part_a + expression_to_add_noise).

In [7]:
import numpy as np



In [12]:
a = np.array(
    [
    [1, 2, 3],
    [3, 2, 1]
    ]
    )   

print(a)

[[1 2 3]
 [3 2 1]]


In [13]:
a.ndim


2

In [14]:
a.shape

(2, 3)

In [15]:
a.size


6

In [16]:
a.dtype

dtype('int32')

In [24]:
np.zeros((3, 4, 3))
for i in np.zeros((3, 4, 3)):
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)
 
    

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0
[0. 0. 0.]
0.0
0.0
0.0


In [22]:
np.random.seed(1)
np.random.randint(1, 10, (3, 4, 2))

array([[[6, 9],
        [6, 1],
        [1, 2],
        [8, 7]],

       [[3, 5],
        [6, 3],
        [5, 3],
        [5, 8]],

       [[8, 2],
        [8, 1],
        [7, 8],
        [7, 2]]])

In [25]:
onedim_array = np.array([1, 2, 3, 4, 5])
multidim_array = np.repeat(onedim_array, 5)
multidim_array

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [9]:
multidim_array = np.tile(onedim_array, (5,1))
multidim_array

NameError: name 'onedim_array' is not defined

In [10]:
another_arr = np.tile(onedim_array, (2, 3, 1))
another_arr

NameError: name 'onedim_array' is not defined

<details>
  <summary>Answer</summary>

  ```python
  import numpy as np

  #set initial population
  N0 = 100
  #set growth rate
  rate = 0.4
  #create array of time points 
  t = np.arange(start=0, stop=10.2, step=0.2)

  #calculate population of colony at the time points in t
  population_size = N0 * np.exp(rate*t)
  print('Population size is: ',population_size)

  #add noise to population at each time point
  population_size_noise = N0 * np.exp(rate*t) + np.random.normal(loc=0, scale=250, size=np.shape(population_size))
  print('Population size with noise is: ',population_size_noise)
  ```
</details>

In [37]:
b = np.array(
    [
    [5, 4, 3, 2, 1, 0],
    [10, 8, 6, 4, 2, 0],
    ]
)
b.T

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [42]:
b.reshape(4, 3)



array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [43]:
b.flatten()

array([ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0])

In [47]:
np.hstack((b, a))

array([[ 5,  4,  3,  2,  1,  0,  1,  2,  3],
       [10,  8,  6,  4,  2,  0,  3,  2,  1]])

In [49]:
np.vstack((b.reshape(4, 3), a))

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0],
       [ 1,  2,  3],
       [ 3,  2,  1]])

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3])

In [52]:
arr2 = np.arange(5, 9)
arr2

array([5, 6, 7, 8])

### 2. Create a multiplication table for the number 6.

In [ ]:
# Your code here

<details>
  <summary>Answer</summary>

  ```python
  rows = np.arange(1, 7)
  columns = rows[:,np.newaxis]
  arr = rows * columns
  arr
  ```
</details>

### 3. Slice `arr` to create the following two arrays:

`arr1` = [4, 12, 3]

`arr2` = [3, 19]

In [ ]:
# Your code here

<details>
  <summary>Answer</summary>

  ```python
  arr = np.array([[4, 12, 98], [12, 11, 92], [3, 19, 60]])
  arr

  arr1 = arr[:,0]
  print(arr1)

  arr2 = arr[2,0:2]
  print(arr2)
  ```
</details>